/* Auto-generated by DimOS ArduinoModule — do not edit */
#ifndef DIMOS_ARDUINO_H
#define DIMOS_ARDUINO_H

/* --- Config --- */
#define DIMOS_BAUDRATE 115200

/* --- Topic enum (shared with C++ bridge) --- */
enum dimos_topic {
    DIMOS_TOPIC_DEBUG = 0,
    DIMOS_TOPIC__LED_CMD = 1,  /* In[Bool] */
    DIMOS_TOPIC__LED_STATE = 2,  /* Out[Bool] */
};

/* --- LCM pubsub layer --- */
#include "dimos_lcm_pubsub.h"

/* --- Message type headers --- */
#include "std_msgs/Bool.h"

/* --- Topic ↔ channel mapping --- */
#ifndef DIMOS_TOPIC_MAPPING_DEFINED
#define DIMOS_TOPIC_MAPPING_DEFINED
typedef struct {
    uint16_t    topic_id;
    const char *channel;
} dimos_topic_mapping_t;
#endif
#define DIMOS_NUM_TOPICS 2
static const dimos_topic_mapping_t _dimos_topic_map[] = {
    { 1, "/led_cmd" },
    { 2, "/led_state" },
};

/* --- Channel name constants --- */
#define DIMOS_CHANNEL__LED_CMD "/led_cmd"
#define DIMOS_CHANNEL__LED_STATE "/led_state"

/* --- Serial transport + LCM integration --- */
#include "dimos_lcm_serial.h"

#endif /* DIMOS_ARDUINO_H */
